name: movies
description: A new Flutter project.
publish_to: 'none' 
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.2
  dio: ^3.0.10
  intl: ^0.16.1

  cupertino_icons: ^0.1.3
  custom_splash: ^0.0.2
  effective_dart: ^1.2.4

  fancy_shimmer_image: ^1.2.0

  infinite_scroll_pagination: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  adaptive_icon_background: assets/images/fundo.png
  android: true
  ios: true
  image_path: "assets/images/images.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/images.png
    - assets/images/fundo.png